version: '3.0'

services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=quanghuy
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=tmdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data


  logstash:
    build:
      context: logstash
    env_file: .env
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipelines/:/usr/share/logstash/pipeline/
      - ./logstash/queries/:/usr/share/logstash/config/queries/
    depends_on:
      - db
      - elasticsearch

#  kibana:
#    image: 'docker.elastic.co/kibana/kibana:7.10.2'
#    ports:
#      - "5601:5601"
#    hostname: kibana
#    depends_on:
#      - elasticsearch

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
